version: '3'
services:

  api_eval:
    build:
      context: api
    image: api-eval
    container_name: be-eval
    ports:
      - "8080:8080"
    
  fe-eval:
    build:
      context: nextjs
    image: fe-eval
    container_name: fe-eval
    ports:
      - "3000:3000"
    